/* Auto-generated by NativeFlow Studio. Do not edit. */
import { LOCALIZATION, mergedFor } from './messages';

const PLURAL_RE = /\{(\w+),\s*plural\s*,([\s\S]+?)\}\s*$/;

function selectPluralCategory(n: number): 'one' | 'other' {
  return n === 1 ? 'one' : 'other';
}

function applyPlurals(template: string, vars: Record<string, any>): string {
  return template.replace(/\{(\w+),\s*plural\s*,([\s\S]+?)\}/g, (_m, varName, body) => {
    const n = Number(vars?.[varName] ?? 0);
    const cat = selectPluralCategory(n);
    const branchRe = new RegExp('(?:^|\\s)(one|other)\\s*\\{([^{}]*)\\}', 'g');
    const branches: Record<string, string> = {};
    let m: RegExpExecArray | null;
    while ((m = branchRe.exec(body)) !== null) branches[m[1]] = m[2];
    const chosen = branches[cat] ?? branches.other ?? '';
    return chosen.replace(/#/g, String(n));
  });
}

function applySimpleVars(template: string, vars?: Record<string, any>): string {
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_m, name) => {
    const v = vars[name];
    return v == null ? '' : String(v);
  });
}

export function formatMessage(template: string, vars?: Record<string, any>): string {
  let out = template;
  if (PLURAL_RE.test(out) || /\{\w+,\s*plural/.test(out)) {
    out = applyPlurals(out, vars || {});
  }
  return applySimpleVars(out, vars);
}

export function lookup(locale: string, key: string): string | undefined {
  const direct = mergedFor(locale)[key];
  if (direct !== undefined) return direct;
  const fb = LOCALIZATION.fallbackLocale;
  if (fb && fb !== locale) {
    const fallback = mergedFor(fb)[key];
    if (fallback !== undefined) return fallback;
  }
  return undefined;
}

export function makeT(locale: string) {
  return function t(key: string, vars?: Record<string, any>): string {
    const tpl = lookup(locale, key);
    if (tpl === undefined) {
      if (typeof __DEV__ !== 'undefined' && __DEV__) return '\u2039' + key + '\u203a';
      return '';
    }
    return formatMessage(tpl, vars);
  };
}
