/* Auto-generated by NativeFlow Studio. Do not edit. */
import React, { createContext, useCallback, useEffect, useMemo, useState } from 'react';
import { I18nManager, Platform } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Localization from 'expo-localization';
import { LOCALIZATION } from './messages';
import { makeT } from './format';
import { hydrateFromCache, refreshRemote } from './remote';

const STORAGE_KEY = '@i18n.locale';

export interface I18nContextValue {
  locale: string;
  setLocale: (next: string) => Promise<void> | void;
  t: (key: string, vars?: Record<string, any>) => string;
  isRTL: boolean;
  supportedLocales: string[];
}

export const I18nContext = createContext<I18nContextValue | null>(null);

function pickInitialLocale(persisted: string | null): string {
  const supported = LOCALIZATION.supportedLocales;
  if (persisted && supported.includes(persisted)) return persisted;
  if (LOCALIZATION.autoDetectDeviceLocale) {
    try {
      const device = (Localization.getLocales?.()[0]?.languageTag) || (Localization as any).locale || '';
      if (device) {
        if (supported.includes(device)) return device;
        const base = device.split('-')[0];
        const baseMatch = supported.find((l) => l === base || l.startsWith(base + '-'));
        if (baseMatch) return baseMatch;
      }
    } catch {}
  }
  return LOCALIZATION.defaultLocale;
}

async function maybeReloadForRTL(nextLocale: string) {
  const nextRTL = LOCALIZATION.rtlLocales.includes(nextLocale);
  if (nextRTL !== I18nManager.isRTL) {
    try {
      I18nManager.allowRTL(nextRTL);
      I18nManager.forceRTL(nextRTL);
      if (Platform.OS !== 'web') {
        try {
          const Updates = await import('expo-updates');
          await Updates.reloadAsync();
        } catch {
          // expo-updates not installed — caller can prompt user to reload.
        }
      }
    } catch {}
  }
}

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<string>(LOCALIZATION.defaultLocale);
  const [ready, setReady] = useState(false);
  // Bumped whenever the remote overlay changes so consumers re-render.
  const [overlayVersion, setOverlayVersion] = useState(0);

  useEffect(() => {
    (async () => {
      let persisted: string | null = null;
      if (LOCALIZATION.persistUserChoice) {
        try { persisted = await AsyncStorage.getItem(STORAGE_KEY); } catch {}
      }
      const initial = pickInitialLocale(persisted);
      // Hydrate any cached remote catalog before first paint so we don't flash bundled copy.
      try { await hydrateFromCache(initial); } catch {}
      setLocaleState(initial);
      setReady(true);
      const strategy = (LOCALIZATION as any).remoteCatalogStrategy;
      if ((LOCALIZATION as any).remoteCatalogUrl && (strategy === 'on-launch' || strategy === 'both')) {
        refreshRemote(initial).then((changed) => { if (changed) setOverlayVersion((v) => v + 1); }).catch(() => {});
      }
    })();
  }, []);

  const setLocale = useCallback(async (next: string) => {
    if (!LOCALIZATION.supportedLocales.includes(next)) return;
    const strategy = (LOCALIZATION as any).remoteCatalogStrategy;
    if ((LOCALIZATION as any).remoteCatalogUrl && (strategy === 'on-locale-change' || strategy === 'both')) {
      // Best-effort fetch with a 2s ceiling so we don't block forever.
      try {
        await Promise.race([
          refreshRemote(next),
          new Promise((r) => setTimeout(r, 2000)),
        ]);
        setOverlayVersion((v) => v + 1);
      } catch {}
    } else {
      try { await hydrateFromCache(next); setOverlayVersion((v) => v + 1); } catch {}
    }
    setLocaleState(next);
    if (LOCALIZATION.persistUserChoice) {
      try { await AsyncStorage.setItem(STORAGE_KEY, next); } catch {}
    }
    await maybeReloadForRTL(next);
  }, []);

  const value = useMemo<I18nContextValue>(() => ({
    locale,
    setLocale,
    t: makeT(locale),
    isRTL: LOCALIZATION.rtlLocales.includes(locale),
    supportedLocales: LOCALIZATION.supportedLocales as unknown as string[],
  }), [locale, setLocale, overlayVersion]);

  if (!ready) return null;
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
