/* Auto-generated by NativeFlow Studio. Do not edit. */
import React from 'react';
import { View, Text, Pressable, StyleSheet } from 'react-native';
import { useTranslation } from './useTranslation';

export function LocaleSwitcher() {
  const { locale, setLocale, supportedLocales } = useTranslation();
  return (
    <View style={styles.row}>
      {supportedLocales.map((l) => (
        <Pressable
          key={l}
          onPress={() => setLocale(l)}
          style={[styles.chip, l === locale && styles.chipActive]}
        >
          <Text style={[styles.label, l === locale && styles.labelActive]}>{l}</Text>
        </Pressable>
      ))}
    </View>
  );
}

const styles = StyleSheet.create({
  row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, padding: 8 },
  chip: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, borderWidth: 1, borderColor: '#d1d5db' },
  chipActive: { backgroundColor: '#111827', borderColor: '#111827' },
  label: { fontSize: 12, color: '#374151' },
  labelActive: { color: '#ffffff' },
});
