/* Auto-generated by NativeFlow Studio. Do not edit. */
import L_en from '../../assets/locales/en.json';

export const MESSAGES: Record<string, Record<string, string>> = {
  'en': L_en as Record<string, string>,
};

export const LOCALIZATION = {
  "defaultLocale": "en",
  "fallbackLocale": "en",
  "supportedLocales": [
    "en"
  ],
  "rtlLocales": [],
  "autoDetectDeviceLocale": true,
  "persistUserChoice": true,
  "numberFormatLocale": "follow-app",
  "remoteCatalogUrl": null,
  "remoteCatalogStrategy": "both",
  "remoteCatalogCacheTtlMinutes": 60
} as const;

/** Mutable runtime overlay populated by lib/i18n/remote.ts. */
export const REMOTE_OVERLAY: Record<string, Record<string, string>> = {};

export function mergedFor(locale: string): Record<string, string> {
  const base = MESSAGES[locale] || {};
  const overlay = REMOTE_OVERLAY[locale];
  return overlay ? { ...base, ...overlay } : base;
}
