/* Auto-generated by NativeFlow Studio. Do not edit. */
import AsyncStorage from '@react-native-async-storage/async-storage';
import { LOCALIZATION, REMOTE_OVERLAY } from './messages';

const CACHE_PREFIX = '@i18n.remote.';

function resolveUrl(locale: string): string | null {
  const tpl = (LOCALIZATION as any).remoteCatalogUrl as string | undefined;
  if (!tpl) return null;
  return tpl.includes('{locale}') ? tpl.replace('{locale}', encodeURIComponent(locale)) : tpl;
}

function ttlMs(): number {
  const m = (LOCALIZATION as any).remoteCatalogCacheTtlMinutes as number | undefined;
  return Math.max(0, (m ?? 60)) * 60 * 1000;
}

function isFlatMap(x: any): x is Record<string, string> {
  if (!x || typeof x !== 'object' || Array.isArray(x)) return false;
  for (const k of Object.keys(x)) if (typeof x[k] !== 'string') return false;
  return true;
}

/** Load cached overlay into REMOTE_OVERLAY (no network). */
export async function hydrateFromCache(locale: string): Promise<boolean> {
  try {
    const raw = await AsyncStorage.getItem(CACHE_PREFIX + locale);
    if (!raw) return false;
    const parsed = JSON.parse(raw) as { at: number; data: Record<string, string> };
    if (!parsed || !isFlatMap(parsed.data)) return false;
    REMOTE_OVERLAY[locale] = parsed.data;
    return true;
  } catch { return false; }
}

/** Fetch fresh overlay (respecting TTL) and persist to cache. Returns true if overlay changed. */
export async function refreshRemote(locale: string): Promise<boolean> {
  const url = resolveUrl(locale);
  if (!url) return false;
  // Skip refresh if cache is still fresh.
  try {
    const raw = await AsyncStorage.getItem(CACHE_PREFIX + locale);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (parsed?.at && Date.now() - parsed.at < ttlMs()) {
        if (isFlatMap(parsed.data)) REMOTE_OVERLAY[locale] = parsed.data;
        return true;
      }
    }
  } catch {}
  try {
    const res = await fetch(url, { headers: { Accept: 'application/json' } });
    if (!res.ok) return false;
    const json = await res.json();
    if (!isFlatMap(json)) return false;
    REMOTE_OVERLAY[locale] = json;
    try { await AsyncStorage.setItem(CACHE_PREFIX + locale, JSON.stringify({ at: Date.now(), data: json })); } catch {}
    return true;
  } catch {
    return false;
  }
}
