/* Auto-generated by NativeFlow Studio. Do not edit. */
import { useContext } from 'react';
import { I18nContext } from './I18nProvider';
import { makeT } from './format';
import { LOCALIZATION } from './messages';

const FALLBACK = {
  locale: LOCALIZATION.defaultLocale,
  setLocale: () => {},
  t: makeT(LOCALIZATION.defaultLocale),
  isRTL: LOCALIZATION.rtlLocales.includes(LOCALIZATION.defaultLocale),
  supportedLocales: LOCALIZATION.supportedLocales as unknown as string[],
};

export function useTranslation() {
  const ctx = useContext(I18nContext);
  return ctx || FALLBACK;
}
